WebWarehouse/Controllers/ItemsController.cs
using log4net;
using System.Web.Mvc;
using WebWarehouse.BLL;
using WebWarehouse.Model;

namespace WebWarehouse.Controllers
{
    public class ItemsController : MyController
    {
        private ItemBLL bll;
        private ItemCategoryBLL icbll;
        private ILog Logger = LogManager.GetLogger(typeof(ItemsController));


        public ItemsController()
        {
            bll = new ItemBLL();
            icbll = new ItemCategoryBLL();
        }

        public ItemsController(ItemBLL stub, ItemCategoryBLL stub2)
        {
            bll = stub;
            icbll = stub2;
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            CheckLoginStatus();
            addCustomMessages();
            ViewBag.ItemCategoryID = new SelectList(icbll.FindAll(), "ID", "Name");
            return View();
        }

        // POST: Items/Create To protect from overposting attacks, please enable the specific
        // properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ItemCategoryID,Name,Price")] Item Item)
        {
            CheckLoginStatus();
            addCustomMessages();
            if (ModelState.IsValid)
            {
                if (bll.Create(Item))
                {
                    var msg = "A new Item was created with name: " + Item.Name;
                    Logger.Info(msg);
                    TempData["SuccessMessage"] = msg;
                    return RedirectToAction("Index");
                }
            }

            ViewBag.ItemCategoryID = new SelectList(icbll.FindAll(), "ID", "Name", Item.ItemCategoryID);
            return View(Item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int id)
        {
            CheckLoginStatus();
            addCustomMessages();

            Item item = bll.Find(id);
            if (item == null)
            {
                var msg = "Could not find the specified Item";
                Logger.Warn(msg);
                TempData["ErrorMessage"] = msg;
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bll.Delete(id);
            return RedirectToAction("Index");
        }

        // GET: Items/Details/5
        public ActionResult Details(int id)
        {
            CheckLoginStatus();
            addCustomMessages();

            Item Item = bll.Find(id);
            if (Item == null)
            {
                var msg = "Cannot find the specified Item -> Did you use the right link?";
                Logger.Warn(msg);
                TempData["ErrorMessage"] = msg;
                return RedirectToAction("Index");
            }
            return View(Item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int id)
        {
            CheckLoginStatus();
            addCustomMessages();

            Item item = bll.Find(id);
            if (item == null)
            {
                var msg = "You must specify which Item you wish to edit";
                Logger.Warn(msg);
                TempData["ErrorMessage"] = msg;
                return RedirectToAction("Index");
            }
            ViewBag.ItemCategoryID = new SelectList(icbll.FindAll(), "ID", "Name", item.ItemCategoryID);
            return View(item);
        }

        // POST: Items/Edit/5 To protect from overposting attacks, please enable the specific
        // properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ItemCategoryID,Name,Price")] Item item)
        {
            CheckLoginStatus();
            addCustomMessages();
            if (ModelState.IsValid)
            {
                if (bll.Update(item))
                {
                    var msg = "You have updated Item with id: " + item.ID;
                    Logger.Info(msg);
                    TempData["SuccessMessage"] = msg;
                    return RedirectToAction("Index");
                }
                else
                {
                    var msg = "Updating the Item with id: " + item.ID + " failed.";
                    Logger.Warn(msg);
                    TempData["ErrorMessage"] = msg;
                    addCustomMessages();
                }
            }
            ViewBag.ItemCategoryID = new SelectList(icbll.FindAll(), "ID", "Name", item.ItemCategoryID);
            return View(item);
        }

        // GET: Items
        public ActionResult Index()
        {
            CheckLoginStatus();
            addCustomMessages();

            return View(bll.FindAll());
        }

        //Custom method to listAllItems with a common ItemCategory
        public ActionResult ListByCategory(int itemCategoryId)
        {

            CheckLoginStatus();
            addCustomMessages();
            var Items = bll.ListByCategory(itemCategoryId);

            ViewBag.CategoryName = icbll.Find(itemCategoryId).Name;
            return View("List", Items);


        }
    }
}

WebWarehouse/Controllers/OrdersController.cs
using log4net;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebWarehouse.BLL;
using WebWarehouse.Model;

namespace WebWarehouse.Controllers
{
    public class OrdersController : MyController
    {
        private OrderBLL bll;
    

        private ILog Logger = LogManager.GetLogger(typeof(OrdersController));

        public OrdersController()
        {
            bll = new OrderBLL();
       
        }

        public OrdersController(OrderBLL stub)
        {
            bll = stub;

        }



        public ActionResult AddItem(int itemid, int userid)
        {
            if (Session != null)
            {
                if (!Session["UserID"].Equals(userid))
                {
                    //invalid userID
                    return Json(new { error = "Invalid userID" }, JsonRequestBehavior.AllowGet);
                }
            }
         
            CheckLoginStatus();
            addCustomMessages();
            if (ModelState.IsValid)
            {
                return Json(new JavaScriptSerializer().Serialize(bll.addItem(itemid, userid)), JsonRequestBehavior.AllowGet);
            }
            return Json(new { error = "Something went wrong, dispatch monkeys to fix" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CheckOut(int orderID)
        {
            CheckLoginStatus();
            addCustomMessages();

            Order checkoutOrder = bll.Find(orderID);

            if (Session["UserID"].Equals(checkoutOrder.user.ID))
            {
                if (checkoutOrder != null)
                {
                    TempData["SuccessMessage"] = "You are now one step away from fulfilling your destiny!";
                    addCustomMessages();
                    return View(checkoutOrder);
                }
                else
                {
                    var msg = "There is no order with orderID: " + orderID;
                    TempData["ErrorMessage"] = msg;
                    Logger.Warn(msg);
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                TempData["ErrorMessage"] = "You are not allowed to check out this order!";
                Logger.Error("User with UserID: " + Session["UserId"] + " is trying to check out another users order.");
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            CheckLoginStatus();
            addCustomMessages();
            return View();
        }

        // POST: Orders/Create To protect from overposting attacks, please enable the specific
        // properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,status,ordered,delivered")] Order order)
        {
            CheckLoginStatus();
            addCustomMessages();
            if (ModelState.IsValid)
            {
                if (bll.Create(order))
                {
                    var msg = "A new Order was created with ID: " + order.ID;
                    Logger.Info(msg);
                    TempData["SuccessMessage"] = msg;
                    return RedirectToAction("Index");
                }
            }

            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int id)
        {
            CheckLoginStatus();
            addCustomMessages();

            Order order = bll.Find(id);
            if (order == null)
            {
                var msg = "Could not find the specified Order";
                Logger.Warn(msg);
                TempData["ErrorMessage"] = msg;
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bll.Delete(id);
            return RedirectToAction("Index");
        }

        // GET: Orders/Details/5
        public ActionResult Details(int id)
        {
            CheckLoginStatus();
            addCustomMessages();

            Order order = bll.Find(id);
            if (order == null)
            {
                var msg = "Cannot find the specified Order -> Did you use the right link?";
                Logger.Error(msg);
                TempData["ErrorMessage"] = msg;
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int id)
        {
            CheckLoginStatus();
            addCustomMessages();

            Order order = bll.Find(id);
            if (order == null)
            {
                var msg = "Cannot find the specified Order -> Did you use the right link?";
                Logger.Error(msg);
                TempData["ErrorMessage"] = msg;
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // POST: Orders/Edit/5 To protect from overposting attacks, please enable the specific
        // properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Status,Ordered,Delivered,UserID")] Order order)
        {
            CheckLoginStatus();
            addCustomMessages();

            if (ModelState.IsValid)
            {
                if (bll.Update(order))
                {
                    var msg = "You have updated Order with id: " + order.ID;
                    Logger.Info(msg);
                    TempData["SuccessMessage"] = msg;
                    return RedirectToAction("Index");
                }
                else
                {
                    var msg = "Updating the order with id: " + order.ID + " failed.";
                    Logger.Warn(msg);
                    TempData["ErrorMessage"] = msg;
                    addCustomMessages();
                }
            }
            return View(order);
        }

        // GET: Orders
        public ActionResult Index()
        {
            CheckLoginStatus();
            addCustomMessages();
            return View(bll.FindAll());
        }

        [HttpGet]
        public ActionResult Reciept(int orderID)
        {
            CheckLoginStatus();
            addCustomMessages();


            Order recieptOrder = bll.Find(orderID);
            if (Session["UserID"].Equals(recieptOrder.user.ID))
            {
                if (recieptOrder != null)
                {
                    recieptOrder.Status = OrderEnum.Payed;
                    recieptOrder.Ordered = System.DateTime.Now;

                    bll.Update(recieptOrder);
                    TempData["SuccessMessage"] = "Congratulations!You have ordered. The shopping cart is emptied, and you can view your exisiting orders by clicking on the menuitem.";
                    Logger.Info("Order with ordreID: " + recieptOrder.ID + " was successfull");
                    addCustomMessages();
                    return View(recieptOrder);
                }
                else
                {
                    var msg = "There is no order with orderID: " + orderID;
                    TempData["ErrorMessage"] = msg;
                    Logger.Warn(msg);
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                TempData["ErrorMessage"] = "You are not allowed to check out this order!";
                Logger.Error("User with UserID: " + Session["UserId"] + " is trying to check out another users order.");
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult RemoveItem(int itemid, int userid)
        {
            if (!Session["UserID"].Equals(userid) && !Session["Role"].Equals(UserRole.Admin.ToString()))
            {
                //invalid userID
                return Json(new { error = "Invalid userID" }, JsonRequestBehavior.AllowGet);
            }
            CheckLoginStatus();
            addCustomMessages();

            if (ModelState.IsValid)
            {
                return Json(new JavaScriptSerializer().Serialize(bll.removeItem(itemid, userid)), JsonRequestBehavior.AllowGet);
            }
            return Json(new { error = "Something went wrong, dispatch monkeys to fix" });
        }
    }
}

WebWarehouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WebWarehouse</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebWarehouse", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
               
                @if (ViewBag.Role.Equals("Admin"))
                    //Navigation Element shown if User is Admin
                {<ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Users")"><i class="fa fa-list fa-fw"></i>List Alle Brukere</a></li>
                     <li><a href="@Url.Action("Index","ItemCategories")"><i class="fa fa-list fa-fw"></i>List Alle Kategorier</a></li>
                     <li><a href="@Url.Action("Index","Items")"><i class="fa fa-list fa-fw"></i>List Alle Varer</a></li>
                     <li><a href="@Url.Action("Index","Orders")"><i class="fa fa-list fa-fw"></i>List Alle Odre</a></li>
                </ul>
                }

               
                <ul class="nav navbar-nav pull-right">
                    @if (ViewBag.LoggedInn == true)
                    {
                        if (ViewBag.Role.Equals("Customer"))
                        {
                              <li><a id="showCart" href="#"><i class="fa fa-shopping-cart fa-fw"></i>Vis Handleliste</a></li>
                        }
                      
                        //Public menu showed if logged in.
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-fw"></i>Min  Bruker<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Edit", "Users", new { id = @ViewBag.UserID })"><i class="fa fa-pencil fa-fw"></i> Rediger</a></li>
                                <li><a href="@Url.Action("Delete", "Users", new { id = @ViewBag.UserID})"><i class="fa fa-trash-o fa-fw"></i> Slett</a></li>
                                <li><a href="@Url.Action("ListAllOrders", "Users", new { id = @ViewBag.UserID})"><i class="fa fa-ban fa-fw"></i> Min Ordrehistorikk</a></li>
                                
                                <li class="divider"></li>
                                <li><a href="@Url.Action("Logout", "Users")"><i class="fa fa-sign-out fa-fw"></i> Logg ut</a></li>
                            </ul>
                        </li>

                    }
                    else
                    {
                        
                        //Menu showed if logged out
                        <li><a href="@Url.Action("Create","Users")"><i class="fa fa-edit fa-fw"></i>Registrer ny bruker</a></li>
                        <li><a href="@Url.Action("Login", "Users")"><i class="fa fa-sign-in fa-fw"></i>Logg Inn</a></li>

                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WebWarehouse</p>
        </footer>
        <div id="globalMessages" data-error="@ViewBag.ErrorMessage" data-success="@ViewBag.SuccessMessage" data-info="@ViewBag.InfoMessage" />
   
    </div>
    <div class="modal fade" id="shoppingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-url="@Url.Action("ActiveOrder", "Users", new { userId = @ViewBag.UserID})">
        <div id="shoppingCart" class="modal-dialog">
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#showCart').click(function () {
                console.log()
                var url = $('#shoppingModal').data('url');
                console.log(url);

                $.get(url, function (data) {

                    console.log("return");
                    $('#shoppingCart').html(data);

                    $('#shoppingModal').modal('show');
                });
            });
        });

    </script>



    
    

</body>
</html>